image: "registry.silkrode.com.tw/team_mobile/mimi:1.0.1"

stages:
  - build

build_job:
  stage: build
  tags:
    - docker
  script:
    - fastlane init_env
    - fastlane build_release_apk
  cache:
    untracked: true
  only:
    - release
